version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend/api_casino
      dockerfile: Dockerfile
    ports:
      - "5296:5296"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=casino;Username=admin;Password=secret
    command: ["dotnet", "api_casino.dll", "--urls", "http://+:5296"]
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: casino
    ports:
      - "55432:5432"
