version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend/api_casino
      dockerfile: Dockerfile
    ports:
      - "5296:5296"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: ["dotnet", "api_casino.dll", "--urls", "http://+:5296"]
