version: '3.8'

services:
  frontend:
    image: monsterelch/casino-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production

  backend:
    image: monsterelch/casino-backend
    ports:
      - "5296:5296"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    command: ["dotnet", "api_casino.dll", "--urls", "http://+:5296"]
